name: GitHub Pages

on:
  push:
    branches: [ pages ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: ${{ secrets.CNAME }}
          publish_dir: ./public
